### ISSUE TITLE
Set Godot function to return an expected Value

### ISSUE THREAD

**Issue by lars-hoeck** [CodeDarigan/WAT#117]
Hey,
I use is_on_floor() in a method
and to test the method i need the is_on_floor() to return false/true

I tried it with director and stub, but couldn't get it working

**Comment by CodeDarigan** [comment]
I created a script that extends from a KinematicBody2D and managed to get this:

![Screenshot from 2020-03-23 17-18-49](https://user-images.githubusercontent.com/47497501/77344340-eec28180-6d2a-11ea-9f74-e9f63a182188.png)

However it seems if you're doubling the KInematicBody2D (probably because you're trying to double a scene that stores code elsewhere so the Body is the default one, then WAT complains).

**Comment by CodeDarigan** [comment]
Added a commit so you can double builtin classes directly. Download the latest master branch and this issue should be solved for you so you can stub to your hearts content.

![Screenshot from 2020-03-23 18-17-57](https://user-images.githubusercontent.com/47497501/77349477-fa19ab00-6d32-11ea-970f-0614fd1ce953.png)

**Comment by CodeDarigan** [comment]
In retrospect, I don't think I've implemented this when doubling a scene (which is probably your issue?).

**Comment by CodeDarigan** [comment]
In retrospect I hadn't fixed this for scene doubling (it would just skip over nodes with no user-defined script) but now WAT creates an empty proxy script in memory instead so you should be able to double this as a scene which has a KInematicBody2D (or whatever you're using) as a child with no script of its own and still stub those builtin methods.

**Comment by CodeDarigan** [comment]
Example:

![Screenshot from 2020-03-23 23-03-57](https://user-images.githubusercontent.com/47497501/77371207-b3d84200-6d5a-11ea-9e33-56c8a7ad145e.png)

**Comment by CodeDarigan** [comment]
I'm assuming this is working fine for you now if you have no problems so I'm going to close it. Inform me otherwise.
