### ISSUE TITLE
C# tests not loading at all

### ISSUE THREAD

**Issue by Atlinx** [CodeDarigan/WAT#305]
On WAT 6.0 and the latest GitHub version, I get the following error when the plugin loads a C# test:
```
res://addons/WAT/filesystem/validator.gd:16 - Invalid call. Nonexistent function 'new' in base 'CSharpScript'
```
I'm using Godot 3.3.2 mono.

I looked into the code and the error doesn't make any sense -- there already is a check for `load(p).has_method("new")` so how is this possible?

**Comment by RailKill** [comment]
https://github.com/AlexDarigan/WAT/pull/319 should cover this. The tests should run properly and it should show up as a failed test case in the results (with "parse error" as the reason). The error message is still vague because Godot's doesn't properly report it or expose the errors, but at least the tests should work.

To answer your question on ```load(p).has_method("new")```, this always returns true because [all Objects in Godot has the .new() instantiator](https://docs.godotengine.org/en/stable/classes/class_object.html). For inherited classes of Script such as [GDScript](https://docs.godotengine.org/en/stable/classes/class_gdscript.html#class-gdscript) and [CSharpScript](https://docs.godotengine.org/en/stable/classes/class_csharpscript.html#class-csharpscript), they actually have their own ```new()``` method which they will call; this is a **shadow** of Object's ```new()```, not an override. Therefore, we cannot use ```has_method("new")``` to check if the script was properly loaded. Tagging @AlexDarigan as well in case he wants to know the reason 😂

Just some additional info that isn't intuitive to find, the Godot docs have a Warning that C# class names and file names must match: https://docs.godotengine.org/en/stable/getting_started/scripting/cross_language_scripting.html) or else it will throw the ```Invalid call. Nonexistent function 'new' in base``` error.
