### ISSUE TITLE
Custom assert messages

### ISSUE THREAD

**Issue by Beefster09** [CodeDarigan/WAT#88]
I think it would be helpful to be able to fail tests with custom assert messages. Sometimes value equality isn't descriptive enough.

**Comment by CodeDarigan** [comment]
I'm a bit lost on this. All assertions have an optional context string you can pass in.

asserts.is_true(value, "expected to be true because whatever")
asserts.is_equal(a, b, "a == b because the same factory method called")

Do you mean something slightly different? If you could give me a code use example it would be great.

**Comment by Beefster09** [comment]
I didn't realize this feature was was already available, more or less. I guess what's needed is more explicit mention of it in the documentation.

One nice addition might be to have a separate pass and fail message if you specify two additional strings or a list containing two strings as the context.

**Comment by CodeDarigan** [comment]
Alright.

I know the documentation isn't up to par so that's my main focus right now. Still going be a while though.
